### ISSUE TITLE
Event 'resize' returns undefined / no data

### ISSUE THREAD

**Issue by Inventsable** [PanJiaChen/vue-split-pane#14]
Hello, love how simple and easy to use this is, but I find the "resize" event emitted not very useful as I have to manually write in my own functionality every time. It would be great if it returned an Object with the current percentage of each pane instead!

**Comment by notchris** [comment]
I would also like to see this.

**Comment by notchris** [comment]
This is now the default behavior.
``` vue
<split-pane @resize="resizeLeft($event)" ref="left" :min-percent='20' :default-percent='50' split="horizontal">
```

` `` javascript
resizeLeft (p) {
      console.log(p); // The updated percent;
      this.$refs.right.percent = p; // You can update other panels by changing the percent property on a set ref.
    }
```
